crypto:
  jwt_secret: ${oc.env:JWT_SECRET}
dynamo:
  table_name: kscale-www-staging-cluster
site:
  homepage: https://dashboard-staging.kscale.dev
  artifact_base_url: https://stagingassets.kscale.dev/
