crypto:
  jwt_secret: fakeJwtSecret
s3:
  bucket: ${oc.env:AWS_S3_BUCKET}
  prefix: ""
dynamo:
  table_name: robolist-local
site:
  homepage: http://127.0.0.1:3000
  artifact_base_url: http://127.0.0.1:4566/artifacts
